### ISSUE TITLE
Select your own email alias

### ISSUE THREAD

**Issue by Snake4life** [denghongcai/forsaken-mail#1]
Hi, awesome trashmail script!

Would it be possible to add a function for the users to select their own mail alias like: myawesomemail@forsaken-mail.com or trashmail@forsaken-mail.com?

**Comment by denghongcai** [comment]
#2

**Comment by denghongcai** [comment]
actually, you can customize your own mail alias through frontend script. I don't add the feature because some special name such as `admin`, `postman` represents special role of your domain.

but if you have better idea to resolve this, any contribute will be great.

**Comment by denghongcai** [comment]
implement in #2
