### ISSUE TITLE
怎么增加数据存储

### ISSUE THREAD

**Issue by GreenJoson** [denghongcai/forsaken-mail#14]
可以增加数据存储吗。我自己用的，这个很简单又好用，但是消息我想存起来，保存一下注册的内容，以防查找，另外后面有邮件进入销毁的邮箱时，还能否收到信息？

**Comment by denghongcai** [comment]
还能的，这个本身实现的就很简单，不会加存储的。
如果你需要存储的话可能需要你自己 fork 开发一下了。
