### ISSUE TITLE
Page web socket make a 400 error

### ISSUE THREAD

**Issue by imfht** [denghongcai/forsaken-mail#5]
I build the this repo var docker and noticed there is a web socket connect get a 400 error.
![image](https://user-images.githubusercontent.com/15059493/39189470-e461fe52-4804-11e8-8eef-503fdb683e3c.png)
how can i fix it?
site: [mail.fht.im](https://mail.fht.im)

**Comment by denghongcai** [comment]
you use cloudflare as cdn. websocket only works when all reverse proxy in the route support.

**Comment by denghongcai** [comment]
and will downgrade to http xhr request
