### ISSUE TITLE
存在xss漏洞

### ISSUE THREAD

**Issue by imfht** [denghongcai/forsaken-mail#6]
使用Gmail发送邮件内容为:
```
<script>alert(/xss/)</script>
<script>alert(/xss/)</script>
<script>alert(/xss/)</script>
```
会在forsaken-mail面板上执行JS代码。
eg:
![image](https://user-images.githubusercontent.com/15059493/43824550-e3f708fe-9b24-11e8-9c9c-49833dc4383d.png)

会考虑修复吗？

**Comment by denghongcai** [comment]
其实当初这只是个小 demo……

你如果有需要的话建议 fork 代码修改一下，粗暴的 HTML ENTITY ENCODE 会破坏展示，想处理好还是挺麻烦的

**Comment by imfht** [comment]
明白，多谢 @denghongcai
