### ISSUE TITLE
希望可以屏蔽部分前缀

### ISSUE THREAD

**Issue by yunfandev** [denghongcai/forsaken-mail#8]
希望可以屏蔽admin前缀，如果没有限制的话，使用者可以签发对应域名的证书😂😂😂

**Comment by denghongcai** [comment]
https://github.com/denghongcai/forsaken-mail/blob/master/modules/io.js#L25

前缀可能要屏蔽的挺多的，可以跑起来之前自己改下，黑名单阻断下或者说干脆用二级域名

**Comment by denghongcai** [comment]
已经增加 keywordBlackList 配置
